# Site settings
title: 와우팜
email: support@wowpharm.kr
description: "신기술을 세상에 적용하고 널리 쓰이도록, 그래서 문화가 바뀌도록, Wow 하도록 돕습니다."
baseurl: ""
url: "http://wowpharm.kr"
twitter_username: wowpharm
github_username:  wowpharm

# Build settings
markdown: kramdown
permalink: pretty
